import type { Metadata } from 'next'
import Template from './component/Template'

export const metadata: Metadata = {
  title: 'Hizratech Konsultan Servis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body><Template >{children}</Template></body>
    </html>
  )
}
