import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Template from './component/Template'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Template>{children}</Template></body>
    </html>
  )
}
